### ISSUE TITLE
Installation failed at `==> opam init --no-setup`.

### ISSUE THREAD

**Issue by mtsg** [nyuichi/homebrew-satysfi#5]
# Description:
When I tried `brew install --HEAD nyuichi/satysfi/satysfi`, installation failed with following:
How should I try next? Thanks.
```
==> opam init --no-setup
Last 15 lines from /Users/mtsg/Library/Logs/Homebrew/satysfi/01.opam:
# sandbox-exec: sandbox_apply_container: Operation not permitted



<><> Error report <><><><><><><><><><><><><><><><><><><><><><><><><><><><><>  🐫 
┌─ The following actions failed
│ λ build ocaml-system 4.07.1
└─ 
┌─ The following changes have been performed (the rest was aborted)
│ ∗ install base-bigarray base
│ ∗ install base-threads  base
│ ∗ install base-unix     base
└─ 
```

## Env. occurred:
- OS
  - macOS Mojave
    - 10.14.2

**Comment by nyuichi** [comment]
@mtsg 

Hi, sorry for the delay, but I have just pushed a patch now. It seems working properly in my environment. What about you?

**Comment by mtsg** [comment]
Sorry for late but thank you for dedication!
I'll try it when the time permitted is.
